cedar:
  build: ./
  ports:
    - "3000:3000"
  command: /rails/poplin_inspector/rails-entrypoint.sh
  links:
    - mongodb:mongo
  env_file: .env-prod
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
